config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
import notifications.urls

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("mva_demo.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("cms/", include("mva_demo.cms.urls", namespace="cms")),
    url("^inbox/notifications/", include(notifications.urls, namespace="notifications")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mva_demo/cms/urls.py
from django.urls import path

from .views import (
    song_all,
    song_detail,
    category_list,
    like_song,
    unlike_song
)

app_name = 'cms'

urlpatterns = [
    path('', song_all, name='song_all'),
    path('<slug:slug>', song_detail, name='song_detail'),
    path('category/<slug:category_slug>/', category_list, name='category_list'),

    path('like/<slug:slug>/', like_song, name="like_song"),
    path('unlike/<slug:slug>/', unlike_song, name="unlike_song")
]

mva_demo/users/urls.py
from django.urls import path

from mva_demo.users.views import (
    user_detail_view,
    user_notification_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~notification/", view=user_notification_view, name="notification"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

mva_demo/cms/models.py
from mva_demo.users.models import User
from django.db import models
from django.urls import reverse

class SongManager(models.Manager):
    def get_queryset(self):
        return super(SongManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('cms:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Song(models.Model):
    category = models.ForeignKey(Category, related_name='song', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='song_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='anonymous')
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    songs = SongManager()

    class Meta:
        verbose_name_plural = 'Songs'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('cms:song_detail', args=[self.slug])

    def __str__(self):
        return self.title

mva_demo/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for mva-demo."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

mva_demo/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

mva_demo/cms/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from notifications.models import Notification
from notifications.signals import notify

from mva_demo.users.models import User

from .models import Category, Song


def song_all(request):
    songs = Song.songs.all()
    return render(request, 'cms/songs/index.html', {'songs': songs})

def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    songs = Song.objects.filter(category=category)
    return render(request, 'cms/songs/category.html', {'category': category, 'songs': songs})

def song_detail(request, slug):
    song = get_object_or_404(Song, slug=slug)
    user = User.objects.get(username=request.user)
    notif = user.notifications.filter(target_object_id=song.id).first()
    like = notif is not None and notif.verb=="like"
    return render(request, 'cms/songs/single.html', {'song': song, 'like': like})

@login_required
@require_POST
def like_song(request, slug):
    song = get_object_or_404(Song, slug=slug)
    sender = User.objects.get(username=request.user)
    notify.send(sender, recipient=song.created_by, target=song, verb='like')
    
    data = {"status": "ok", "target": song.slug, "action": "like"}
    return JsonResponse(data, safe=False)

@login_required
@require_POST
def unlike_song(request, slug):
    song = get_object_or_404(Song, slug=slug)
    sender = User.objects.get(username=request.user)
    notify.send(sender, recipient=song.created_by, target=song, verb='unlike')

    data = {"status": "ok", "target": song.slug, "action": "unlike"}
    return JsonResponse(data, safe=False)

mva_demo/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView
from notifications.views import AllNotificationsList

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserNotificationsList(AllNotificationsList):
    template_name = 'users/user_notifications.html'

user_notification_view = UserNotificationsList.as_view()

mva_demo/templates/base.html
{% load static i18n notifications_tags %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}mva-demo{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Behold My Awesome Project!">
    <meta name="author" content="d1t2">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS and its dependencies-->
      <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="{% static 'notifications/notify.js' %}"></script>

      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">mva-demo</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cms:song_all' %}">Songs</a>
            </li>
            {% if request.user.is_authenticated %}              
              <li class="nav-item btn-group dropdown">
                <a href="{% url 'users:notification' %}" class="notification nav-link btn-secondary" role="button">
                  <i class="fa fa-bell"></i>
                  <span class="badge">{% live_notify_badge %}</span>
                </a>
                <a href="#" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" role="button"
                    id="notifMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="sr-only">Toggle Dropdown</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="notifMenu">
                  {% for notification in  user.notifications.unread %}
                    <div><i class="far fa-comment-dots"></i>
                      Message from <b>{{ notification.actor }}</b>
                      <a href="#" class="dropdown-item">{{ notification.verb }} <b>{{notification.target}}</b></a>
                    </div>
                    <div class="dropdown-divider"></div>
                  {% endfor %}
                  <a class="dropdown-item" href="{% url 'notifications:mark_all_as_read' %}"><i class="fas fa-check-double" title="Mark all read"></i> Clear all</a>
                </div>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
    {% endblock inline_javascript %}
  </body>
</html>

mva_demo/templates/cms/home.html
{% extends "base.html" %}
{% block content %}
{% for song in songs %}
<div class="col">
  <div class="card shadow-sm">
    <div class="card-body">
      <p class="card-text">
        <a class="text-dark text-decoration-none" href="{{ song.get_absolute_url }}">{{ song.title }}</a>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted">{{ song.category }}</small>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted">{{ song.author }}</small>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

mva_demo/templates/cms/songs/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<main>
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for song in songs %}

        <div class="col">
          <div class="card shadow-sm">

            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ song.get_absolute_url }}">{{ song.title }}</a>
              </p>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

mva_demo/templates/cms/songs/index.html
{% extends "base.html" %}
{% block content %}
{% for song in songs %}
<div class="col">
  <div class="card shadow-sm">
    <div class="card-body">
      <p class="card-text">
        <a class="text-dark text-decoration-none" href="{{ song.get_absolute_url }}">{{ song.title }}</a>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted">{{ song.category }}</small>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <small class="text-muted">{{ song.author }}</small>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

mva_demo/templates/cms/songs/single.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ song.name }}
{% endblock %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4"><i class="fa-star" title="like this song"></i>{{ song.title }}</h1>
                {% csrf_token %}
                <p />
                <p><span class="lead"><a class="text-dark text-decoration-none"
                        href="{{ song.category.get_absolute_url }}">{{ song.category }}</a></span> (Category)</p>
                <p><span class="lead">{{ song.author }}</span> (Author)</p>
                <p>{{ song.description|slice:":140" }}...</p>
            </div>
        </div>
    </main>
</div>

<script>
window.addEventListener("load", function() {
    $("i.fa-star")
        .addClass(
            {% if like %}
                "fas"  // filled star
            {% else %}
                "far"  // hollow star
            {% endif %})
        .click(function(){
            tell_this_song($(this),
                            ($(this).hasClass("far")) ? "like" : "unlike",
                            '{{song.slug}}');
        });
});

function tell_this_song(el, verb, slug) {
    const defaults = {
        'method': 'POST',
        'credentials': 'same-origin',
        'headers': new Headers({
          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
          'Accept': 'application/json',
          'Content-Type': 'application/json',
          'X-Requested-With': 'XMLHttpRequest'
        }),
    };
    var api = "/cms/" + verb + "/" + slug + "/"
    fetch(api, defaults)
    .then(function(response) {
        return response.json();      
    }).then(function(data) {
        console.log("Data is ok", data);
        $(el).toggleClass("fas far")
            .prop('title', (verb == 'like') ? 'Unlike this song' : 'Like this song');
    }).catch(function(ex) {
        console.log("parsing failed", ex);
    });
};
</script>
{% endblock %}

mva_demo/templates/pages/about.html
{% extends "base.html" %}

mva_demo/templates/pages/home.html
{% extends "base.html" %}

mva_demo/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

mva_demo/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

mva_demo/templates/users/user_notifications.html
{% extends "base.html" %}
{% block title %}{{ user.username }}'s Notifications{% endblock %}
{% block content %}
{% for notice in notifications %}
  <div class="col">
    <div class="card shadow-sm">
      <div class="card-body alert alert-{{ notice.level }}">
          <a class="close pull-right fas fa-times"
              href="{% url 'notifications:mark_as_read' notice.slug %}"></a>
          
          <p class="card-text">
            <i class="icon-mail{% if notice.unread %}-alt{% endif %}"></i>
            {{ notice.actor }} 
            {{ notice.verb }}
            {% if notice.target %}
              of {{ notice.target }}
            {% endif %}
          </p>
          
          <small>{{ notice.timesince }} ago</small>
          
          <div>{{ notice.description|linebreaksbr }}</div>
          
          <div class="notice-actions">
            {% for action in notice.data.actions %}
              <a class="btn" href="{{ action.href }}">{{ action.title }}</a>
            {% endfor %}
          </div>
      </div>
    </div>
  </div>
{% endfor %}
{% endblock %}